name: "TV IP Fixer"
version: "1.1.0"
slug: "tvip_fixer"
description: "Fixes TV IP in config entries"
url: "https://github.com/tinkermesomething/ha-tvip-fixer"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: "ghcr.io/tinkermesomething/tvip-fixer-{arch}"
init: false
map:
  - homeassistant:rw
startup: application
boot: auto